# Generated by Django 2.2.12 on 2020-09-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200911_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
