# Generated by Django 2.2.12 on 2020-09-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_delete_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achievement', models.CharField(max_length=100)),
            ],
        ),
    ]
