# Generated by Django 2.2.12 on 2020-09-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100)),
                ('user_id', models.PositiveSmallIntegerField(default=0)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
