# Generated by Django 2.2.12 on 2020-09-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Login'),
        ),
    ]
